//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookshelf
    {
        public bookshelf()
        {
            this.shelfmanages = new HashSet<shelfmanage>();
        }
    
        public int shelfid { get; set; }
        public string shelfname { get; set; }
        public string shelfdescription { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string update_by { get; set; }
    
        public virtual ICollection<shelfmanage> shelfmanages { get; set; }
    }
}
