//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore_management_system
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookShopEntities3 : DbContext
    {
        public BookShopEntities3()
            : base("name=BookShopEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<discount_type> discount_type { get; set; }
        public DbSet<exportproduct> exportproducts { get; set; }
        public DbSet<importproduct> importproducts { get; set; }
        public DbSet<orderdetail> orderdetails { get; set; }
        public DbSet<payment_methods> payment_methods { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<shift> shifts { get; set; }
        public DbSet<orderp> orderps { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<bookshelf> bookshelves { get; set; }
        public DbSet<shelfmanage> shelfmanages { get; set; }
        public DbSet<discount> discounts { get; set; }
    }
}
