//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.orderps = new HashSet<orderp>();
            this.discounts = new HashSet<discount>();
        }
    
        public int customerid { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<decimal> point { get; set; }
        public Nullable<int> returncount { get; set; }
        public Nullable<System.DateTime> datein { get; set; }
    
        public virtual ICollection<orderp> orderps { get; set; }
        public virtual ICollection<discount> discounts { get; set; }
    }
}
