//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount
    {
        public string discount_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<decimal> min_amount { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> apply_count { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string updated_by { get; set; }
        public Nullable<int> discount_type_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string condition { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> out_date { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual discount_type discount_type { get; set; }
        public virtual product product { get; set; }
    }
}
