//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderp
    {
        public orderp()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public long orderid { get; set; }
        public byte[] barcode { get; set; }
        public long staffid { get; set; }
        public int paycustomerid { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<decimal> totalamount { get; set; }
        public string discountused { get; set; }
    
        public virtual ICollection<orderdetail> orderdetails { get; set; }
        public virtual customer customer { get; set; }
        public virtual staff staff { get; set; }
    }
}
