//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_methods
    {
        public payment_methods()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public int payment_method_id { get; set; }
        public string payment_method_name { get; set; }
    
        public virtual ICollection<orderdetail> orderdetails { get; set; }
    }
}
