//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.exportproducts = new HashSet<exportproduct>();
            this.importproducts = new HashSet<importproduct>();
            this.orderdetails = new HashSet<orderdetail>();
            this.shelfmanages = new HashSet<shelfmanage>();
            this.discounts = new HashSet<discount>();
        }
    
        public int productid { get; set; }
        public string productname { get; set; }
        public Nullable<int> categoryid { get; set; }
        public byte[] barcode { get; set; }
        public byte[] imgpath { get; set; }
        public string description { get; set; }
        public Nullable<decimal> unitprice { get; set; }
        public Nullable<int> quantityinstock { get; set; }
        public string publishing_company { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string update_by { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<exportproduct> exportproducts { get; set; }
        public virtual ICollection<importproduct> importproducts { get; set; }
        public virtual ICollection<orderdetail> orderdetails { get; set; }
        public virtual ICollection<shelfmanage> shelfmanages { get; set; }
        public virtual ICollection<discount> discounts { get; set; }
    }
}
