//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class shelfmanage
    {
        public int shelfmanageid { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> shelfid { get; set; }
        public Nullable<int> quantityinshelf { get; set; }
        public string productname { get; set; }
        public string shelfname { get; set; }
    
        public virtual bookshelf bookshelf { get; set; }
        public virtual product product { get; set; }
    }
}
