//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.orderps = new HashSet<orderp>();
        }
    
        public long id { get; set; }
        public byte[] avatar { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string sex { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string cccd { get; set; }
        public string address { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> shift_id { get; set; }
        public Nullable<decimal> luongcoban { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<orderp> orderps { get; set; }
        public virtual role role { get; set; }
        public virtual shift shift { get; set; }
    }
}
